version: 2
updates:
  # Terraform - local config
  - package-ecosystem: "terraform"
    directory: "/terraform/local"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "terraform"

  # Terraform - azure config
  - package-ecosystem: "terraform"
    directory: "/terraform/azure"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "terraform"

  # Terraform - shared module
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/train-routing"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "terraform"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
